/* ============================================================
   CS214 Revise — glossary data
   src:  'course'    — the term (and its meaning) is in the CS214 slides/labs; `where` says which
         'textbook'  — only in the prescribed text (Neapolitan & Naimipour), not in the slides
         'noncourse' — standard CS vocabulary the course material never uses; here to help, not to quote
   alt:  other spellings/forms that should also get a tooltip
   see:  a page in this site where it is taught (only set for pages that exist)
   ============================================================ */
const GLOSSARY = [
  /* ---------- graphs (Lec 6.1, Lec 9.1) ---------- */
  { w:'vertex', alt:['vertices','node','nodes'], src:'course', where:'Lec 6.1', see:'#/graphs',
    d:'A point in a graph — drawn as a circle. In the slides vertices are named v1, v2, … and the set of all of them is **V**.' },
  { w:'edge', alt:['edges','arc','arcs'], src:'course', where:'Lec 6.1', see:'#/graphs',
    d:'A line from one vertex to another (the slides also call it an **arc**). Written as a pair, e.g. (v1, v2).' },
  { w:'directed graph', alt:['digraph','directed'], src:'course', where:'Lec 6.1', see:'#/graphs',
    d:'A graph where every edge has a direction (an arrow). You may only travel along an edge the way its arrow points.' },
  { w:'undirected graph', alt:['undirected'], src:'course', where:'Lec 9.1', see:'#/graphs',
    d:'A graph whose edges have no direction — an edge between u and v can be used both ways.' },
  { w:'weighted graph', alt:['weight','weights'], src:'course', where:'Lec 6.1', see:'#/graphs',
    d:'A graph whose edges carry values (**weights**) — a cost, distance or time.' },
  { w:'path', alt:['paths'], src:'course', where:'Lec 6.1', see:'#/graphs',
    d:'A sequence of adjacent vertices. In a weighted graph its **length** is the sum of the weights on it.' },
  { w:'simple path', src:'course', where:'Lec 6.1', see:'#/graphs',
    d:'A path that never passes through the same vertex twice. A shortest path is always a simple path.' },
  { w:'cycle', alt:['cycles','acyclic'], src:'course', where:'Lec 6.1 / 9.1', see:'#/graphs',
    d:'A simple path of three or more vertices where the last vertex is adjacent to the first — you can go round and come back. A graph with no cycles is **acyclic**.' },
  { w:'connected', src:'course', where:'Lec 9.1', see:'#/graphs',
    d:'An undirected graph is connected if there is a path between every pair of vertices.' },
  { w:'tree', see:'#/mst', src:'course', where:'Lec 9.1',
    d:'An acyclic, connected, undirected graph.' },
  { w:'spanning tree', see:'#/mst', src:'course', where:'Lec 9.1',
    d:'A connected subgraph that contains **all** the vertices of the given graph and is a tree (so it has n − 1 edges and no cycles).' },
  { w:'minimum spanning tree', alt:['MST'], see:'#/mst', src:'course', where:'Lec 9.1',
    d:'A spanning tree with the smallest possible total weight. Found by Prim\'s or Kruskal\'s algorithm.' },
  { w:'adjacency matrix', src:'course', where:'Lec 9.1 / 9.2', see:'#/graphs',
    d:'An n × n table W where W[i][j] is the weight of the edge from vi to vj, ∞ if there is no edge, and 0 on the diagonal.' },

  /* ---------- problem types & design approaches ---------- */
  { w:'optimization problem', alt:['optimisation problem'], see:'#/greedy-dp', src:'course', where:'Lec 6.1',
    d:'A problem with many candidate solutions, each with a value; a solution is any candidate with the optimal (minimum or maximum) value.' },
  { w:'principle of optimality', see:'#/greedy-dp', src:'course', where:'Lec 6.1 / 6.2',
    d:'"An optimal solution to an instance of a problem always contains optimal solutions to all sub-instances." Needed for dynamic programming.' },
  { w:'greedy algorithm', alt:['greedy approach','greedy'], src:'course', where:'Lec 8.1', see:'#/design',
    d:'Builds a solution by a sequence of decisions, each of which simply looks like the best decision **at that moment** (locally optimal), hoping to end up globally optimal. It never goes back on a choice.',
    ex:'Change for 75c with the biggest coin first: 50 + 20 + 5.' },
  { w:'greedy choice', alt:['locally optimal'], see:'#/huff-algo', src:'course', where:'Lec 8.1 (as "locally optimal choice")',
    d:'The choice a greedy algorithm makes at each step: the one that looks best right now, ignoring what comes later. The slides call it the "locally optimal choice".' },
  { w:'selection procedure', src:'course', where:'Lec 8.1', see:'#/design',
    d:'Step 1 of every greedy iteration: choose the next item by the greedy criterion (e.g. the vertex with the smallest distance).' },
  { w:'feasibility check', src:'course', where:'Lec 8.1', see:'#/design',
    d:'Step 2 of a greedy iteration: check the chosen item can still lead to a solution (e.g. Kruskal: the edge must not make a cycle).' },
  { w:'solution check', src:'course', where:'Lec 8.1', see:'#/design',
    d:'Step 3 of a greedy iteration: check whether the solution is complete (e.g. Y == V).' },
  { w:'dynamic programming', alt:['DP'], see:'#/design', src:'course', where:'Lec 6.1',
    d:'Divide the instance into smaller instances, but solve the small ones **first**, store the results and look them up instead of recomputing them — a bottom-up approach.' },
  { w:'divide and conquer', alt:['divide-and-conquer','D&C'], see:'#/design', src:'course', where:'Lec 4.1',
    d:'A top-down approach: divide an instance into one or more smaller instances, solve (conquer) each recursively, and combine the results if needed.',
    ex:'Binary search, mergesort, quicksort.' },
  { w:'brute force', see:'#/design', src:'course', where:'Lec 6.2 / 7.1 (named, not defined)',
    d:'Try every possible candidate and keep the best. The slides list it as a design approach but do not define it further.' },
  { w:'bottom-up', see:'#/design', src:'course', where:'Lec 6.1',
    d:'Solve the smallest instances first and build up to the full answer (dynamic programming).' },
  { w:'top-down', see:'#/design', src:'course', where:'Lec 4.1',
    d:'Start from the full instance and split it downwards (divide and conquer).' },

  /* ---------- shortest paths (Lec 9.2) ---------- */
  { w:'single-source shortest path', alt:['SSSP','single source shortest path'], src:'course', where:'Lec 9.2', see:'#/sssp',
    d:'Given a graph and one source vertex s, find the shortest path from s to **every** vertex.' },
  { w:'Dijkstra\'s algorithm', alt:['Dijkstra','Dijkstra’s algorithm'], src:'course', where:'Lec 9.2', see:'#/dijkstra',
    d:'A greedy algorithm for single-source shortest paths: repeatedly add to Y the vertex with the shortest path from the source using only vertices in Y as intermediates.' },
  { w:'source vertex', alt:['source'], src:'course', where:'Lec 9.2', see:'#/sssp',
    d:'The starting vertex for single-source shortest paths (v1 in the slides; W in the 2025 test).' },
  { w:'intermediates', alt:['intermediate vertices','intermediate'], src:'course', where:'Lec 9.2', see:'#/dijkstra',
    d:'The vertices a path passes through between its start and end. Dijkstra only allows vertices already in Y as intermediates when it picks the next vertex.' },
  { w:'relaxation', alt:['relax','relaxing','relaxed'], src:'noncourse', see:'#/dijkstra',
    d:'The usual textbook-wide name for the update step: if dist(u) + w(u,v) is smaller than v\'s current distance, replace it (and v\'s predecessor becomes u). The CS214 slides do this step but never name it.' },
  { w:'tentative distance', alt:['distance so far'], src:'noncourse', see:'#/dijkstra',
    d:'A vertex\'s current best-known distance while the algorithm is still running. It can still go down until the vertex is selected; then it is final.' },
  { w:'predecessor', alt:['superscript'], src:'course', where:'Lec 9.2 slide 7 (as the superscript)', see:'#/dijkstra',
    d:'The vertex you arrive from on the best path found so far. The lecturer writes it as a superscript: 7¹ means "distance 7, coming from vertex 1".' },
  { w:'negative weight', alt:['negative weights','negative edge'], src:'noncourse', see:'#/dijkstra',
    d:'An edge with weight below zero. Dijkstra can give wrong answers when there are negative weights. Not mentioned in the CS214 slides — every example there is non-negative.' },

  /* ---------- MST (Lec 9.1) ---------- */
  { w:'Prim\'s algorithm', alt:['Prim','Prim’s algorithm'], see:'#/prim', src:'course', where:'Lec 9.1',
    d:'Greedy MST algorithm: start with Y = {v1}; repeatedly add the vertex in V − Y **nearest to Y** (and that edge to F) until Y = V.' },
  { w:'Kruskal\'s algorithm', alt:['Kruskal','Kruskal’s algorithm'], see:'#/kruskal', src:'course', where:'Lec 9.1',
    d:'Greedy MST algorithm: one disjoint subset per vertex; inspect edges in nondecreasing weight order; add an edge if it joins two different subsets (then merge them); stop when one subset is left.' },
  { w:'disjoint subsets', alt:['disjoint sets','disjoint subset'], see:'#/kruskal', src:'course', where:'Lec 9.1',
    d:'Sets with no vertex in common. Kruskal starts with one per vertex and merges two whenever it accepts an edge between them.' },
  { w:'nearest vertex', alt:['nearest to Y'], see:'#/prim', src:'course', where:'Lec 9.1',
    d:'In Prim: a vertex in V − Y joined to some vertex in Y by an edge of minimum weight.' },
  { w:'union-find', alt:['union find','disjoint-set data structure'], see:'#/kruskal', src:'noncourse',
    d:'A data structure for Kruskal\'s "are these in the same subset? / merge them" steps. The slides describe the idea (disjoint subsets) but not this structure.' },
  { w:'cut property', see:'#/mst', src:'noncourse',
    d:'The standard reason Prim and Kruskal are correct: the lightest edge crossing any split of the vertices into two groups belongs to some MST. Not in the CS214 material.' },

  /* ---------- Huffman (Lec 8.1/8.2) ---------- */
  { w:'priority queue', alt:['priority queues','PQ'], see:'#/huff-algo', src:'course', where:'Week 3 / Lec 8.2',
    d:'A queue where every item has a priority and the highest-priority item leaves first. In Huffman\'s algorithm the highest priority is the **lowest frequency**.' },
  { w:'heap', see:'#/huff-algo', src:'course', where:'Week 3 / Lec 8.2',
    d:'A complete binary tree where each node is ≤ (or ≥) its children — the efficient way to implement a priority queue.' },
  { w:'Huffman code', alt:['Huffman coding','Huffman'], see:'#/huff-algo', src:'course', where:'Lec 8.2',
    d:'An optimal prefix code built by Huffman\'s greedy algorithm: repeatedly join the two lowest-frequency nodes.' },
  { w:'prefix code', alt:['prefix codes','prefix-free'], see:'#/huff-problem', src:'course', where:'Lec 8.2',
    d:'A variable-length code where no codeword is the beginning of another one, so a bit string can be decoded without separators.',
    ex:'If A = 01, no other character may start with 01 (so 011 is not allowed).' },
  { w:'codeword', alt:['codewords'], see:'#/huff-problem', src:'course', where:'Lec 8.2',
    d:'The binary string that represents one character.' },
  { w:'fixed-length code', see:'#/huff-problem', src:'course', where:'Lec 8.2',
    d:'Every character uses the same number of bits (e.g. A 00, B 01, C 11).' },
  { w:'variable-length code', see:'#/huff-problem', src:'course', where:'Lec 8.2',
    d:'Characters use different numbers of bits — common characters get shorter codewords.' },
  { w:'Huffman tree', src:'course', where:'Lec 8.2', see:'#/huff-algo',
    d:'The binary tree Huffman’s algorithm builds. Every symbol is a leaf; each internal node’s weight is the sum of its children. A symbol’s code is its path from the root: left = 0, right = 1.' },
  { w:'frequency', alt:['frequencies'], src:'course', where:'Lec 8.2', see:'#/huff-problem',
    d:'How many times a character occurs in the file. Huffman’s algorithm starts from the frequency of every character.' },
  { w:'code table', src:'course', where:'Lec 8.2 slide 19; Lab 9 solution photos', see:'#/huff-algo',
    d:'The finished list of characters with their frequencies and codewords. Test 2 (2025) Q1 gives one and asks you to work backwards to the tree.' },
  { w:'encoding', alt:['encode','encoded'], src:'course', where:'Lec 8.1', see:'#/huff-encode',
    d:'Turning the file into bits by replacing each character with its codeword (Lec 8.1 "Encoding Data").' },
  { w:'decoding', alt:['decode','decoded','parsing'], src:'course', where:'Lec 8.2 (as "parsing prefix codes")', see:'#/huff-encode',
    d:'Turning bits back into characters. The slides call it **parsing**: start at the root, go left on 0 and right on 1, and when you reach a leaf write its character and go back to the root.' },
  { w:'compression ratio', src:'course', where:'Lab 9 solution photos', see:'#/huff-encode',
    d:'Original size ÷ encoded size, written like 3 : 1. The lab photos use 8 bits per character for the original size.',
    ex:'ISSUE WITH TISSUE: 120 ÷ 40 = 3, so 3 : 1.' },
  { w:'compressed size', src:'noncourse', see:'#/huff-encode',
    d:'Encoded size as a percentage of the original: encoded ÷ original × 100. This is the number the lab photos label "% compression" (40/120 = 33.33%) — it is how big the file still is, not how much was removed.' },
  { w:'space saved', src:'noncourse', see:'#/huff-encode',
    d:'100% − compressed size: how much smaller the file got. ISSUE WITH TISSUE: 100 − 33.33 = 66.67% saved.' },
  { w:'recursive property', src:'course', where:'Lec 6.1', see:'#/design',
    d:'The formula that gives the solution to an instance in terms of smaller instances — step 1 of dynamic programming (e.g. B[i][j] = B[i−1][j−1] + B[i−1][j]).' },
  { w:'overlapping subproblems', alt:['overlap','overlapping'], src:'noncourse', see:'#/design',
    d:'When the same smaller instance is needed again and again. The slides say "same instances are being solved in each recursion" (Lec 6.1). It is the sign that dynamic programming beats divide and conquer.' },
  { w:'optimal substructure', src:'noncourse', see:'#/greedy-dp',
    d:'The usual name elsewhere for the course’s **principle of optimality**: an optimal solution is built from optimal solutions to its sub-instances.' },
  { w:'binomial coefficient', src:'course', where:'Lec 6.1', see:'#/rec-drill',
    d:'C(n, k): the number of ways to choose k items from n. Lec 6.1’s dynamic programming example, filled bottom-up in an array B.' },
  { w:'coin change', src:'course', where:'Lec 8.1', see:'#/greedy-dp',
    d:'Give change with the fewest coins. Greedy (largest coin first) is optimal for 50c/20c/10c/5c/2c/1c but not for 12c/10c/5c/1c (16c: 5 coins instead of 3).' },
  { w:'sparse graph', alt:['sparse'], src:'textbook', see:'#/compare',
    d:'A graph with few edges compared with the most possible (m close to n). The textbook favours Kruskal here.' },
  { w:'dense graph', alt:['dense'], src:'textbook', see:'#/compare',
    d:'A graph with nearly every possible edge (m close to n²). The textbook favours Prim here.' },
  { w:'recurrence', alt:['recurrence relation'], src:'noncourse', see:'#/rec-drill',
    d:'A formula defining f(n) in terms of f on smaller inputs, like f(n) = f(n/2) + (n − 1). The slides call such a formula a recursive property or just "the formula".' },
  { w:'every-case time complexity', alt:['every-case'], src:'course', where:'Weeks 2–3 (analysis); Sample Test I',
    d:'The number of basic operations when it is the same for every input of size n, written T(n) — e.g. Θ(n²) for Dijkstra and Prim in the textbook.' }
];
